name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    strategy:
      matrix:
        jdk: [ 23 ]
=======
    permissions:
      contents: write
      pull-requests: write
      checks: write
>>>>>>> 4ae4636f28ff71f57de07b99d093505363ac16bc
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.2
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1828558443 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'